steps:
  - label: ":pencil: echo agent 1"
    command: echo "agent testing"
    agents:
      - "queue=testing"
      
  - block: "Release"
    prompt: "Fill out the details for release"
    fields: 
    - select: "Type"
      key: "release-type"
      default: "beta"
      options:
      - label: "Beta"
        value: "beta"
      - label: "Stable"
        value: "stable"

  - label: ":pencil: echo release-type"
    command: echo "agent $RELEASE_TYPE"
    agents:
      - "queue=testing"
    env:
      RELEASE_TYPE: $(buildkite-agent meta-data get release-type)