steps:
  # Step 1. Make a lint of the project for avoiding any linting errors.
  - label: "Project linting"
    command: echo "make lint"
    agents:
      - "queue=testing"
  
  # Step 2. Wait for the linting to finish, fail the build if step 1. is failed
  - wait: ~
    continue_on_failure: false

  # Step 3. Select the target on which terraform plan needs to be run
  - command: ./.buildkite/generate-targets.sh | buildkite-agent pipeline upload 
    label: ":file_folder: Select the target directory"
    agents:
      - "queue=testing" 
  

  # Step 4. Wait for the step 3 input
  - wait: ~
    continue_on_failure: false

  # Step 5. Using target directory as account path, generate terraform plan and apply target
  - command: ./.buildkite/generate-terraform.sh
    label: ":terraform: generating terraform steps"
    agents:
      - "queue=testing" 
